---

# Copyright (C) 2019 Intel Corporation
# SPDX-License-Identifier: BSD-3-Clause

kernel_arguments: diskencrypt=false release=prod ubuntuversion=jammy arch=amd64 kernelversion=linux-oem-22.04=5.17.0.1003.3 mirror=http://10.55.10.227/files/Ubuntu_22.04_Desktop/ubuntu/  username=sys-admin password=P@ssw0rd! epassword=\$6\$RsDAmpXBiF8Ev5ub\$BCEVoMK/MKdUQpJEykScLOgx9S8jw4TZCQyKutCfDQ06Dbk24E1u//ofUWFl39zRTyU8Ex45k634JjNDqCTJh.
